name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs: 
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o código
        uses: actions/checkout@v4.2.2
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: | 
            walysonsilva/fake-shop:latest
            walysonsilva/fake-shop:v${{ github.run_number }}
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
       - name: Obter o código
         uses: actions/checkout@v4.2.2
       - uses: azure/k8s-set-context@v4
         with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_KUBECONFIG}}
       - uses: Azure/k8s-deploy@v5
         with:
           manifests: |
             k8s/deployment.yml
           images: walysonsilva/fake-shop:v${{ github.run_number }}
    
    

