name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs: 
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "obter codigo"
      - run: echo "executar docker build"
      - run: echo "enviar imagem para Dockerhub"
  CD:
    runs-on: ubuntu-latest
    steps:
      - run: echo "obter codigo"
      - run: echo "configurar kubeconfig"
      - run: echo "Executar o apply"
    
    

