name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs: 
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o código
        uses: actions/checkout@v4.2.2
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./src
          push: true
          file: ./src
          tags: walysonsilva/fake-shop:v2
      - run: echo "executar docker build"
      - run: echo "enviar imagem para Dockerhub"
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - run: echo "obter codigo"
      - run: echo "configurar kubeconfig"
      - run: echo "Executar o apply"
    
    

